
[pytest]
markers =
    ci_mini: Keep the mark
    regression: Run regression cases
    gcuRegression: Run regression cases on emu
    sanity: Run sanitycase
    gcuSanity: Run sanity cases on emu
    full: Run full test case
